prebuilt feature initial
OpenHisiIpCam/cctv pull request #6
Opened 2021-08-30 22:11 UTC by nikitos1550

Feature than reduce build time by excluding repeating common host tools build.

2021-08-30 22:14 UTC, nikitos1550 commented
Typical build time after feature enable:
`
real	6m8.063s
user	11m41.140s
sys	1m44.254s
`

2021-08-31 07:46 UTC, nikitos1550 commented
host-bison, host-flex can be added to packages list.

2021-08-31 13:10 UTC, wsnk requested changes
defconfig for prebuilt is missed

2021-08-31 13:10 UTC, wsnk commented on prebuilt/pack.sh
> +
It'd be better to give human-readable names to source & output dirs rather than use `$1` and `$2` below

2021-08-31 13:10 UTC, wsnk commented on prebuilt/pack.sh
> +        echo "WARNING: ${path}/.files-list-staging.txt is not null!"
I'd recommend either output such warnings into stderr or fail the whole process.

2021-08-31 13:10 UTC, wsnk commented on prebuilt/Makefile
> +
It might be less code and better readability if you defined a variable like `PREBUILT_OUTPUT_DIR` instead of using of `$(abspath ../output/prebuilt)`

2021-08-31 13:10 UTC, wsnk commented on configs/Makefile
> +	rm -f $(shell find . -name "*_defconfig" ! -name "prebuilt_defconfig")
Seems that `prebuilt_defconfig` is missed

2021-09-01 13:44 UTC, wsnk approved these changes

2021-09-01 13:48 UTC, merged